project:
  type: website

website:
  title: "Maitreyi Pillai"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About Me
      - research.qmd
        text: Research

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

